import React from 'react';
import Immutable from 'immutable';
import { Alert, Button, Col, ControlLabel, FormGroup, HelpBlock, Row } from 'react-bootstrap';

import { Input } from 'components/bootstrap';
import PermissionSelector from 'components/users/PermissionSelector';
import PermissionsMixin from 'util/PermissionsMixin';

const EditRole = React.createClass({
  propTypes: {
    initialRole: React.PropTypes.object,
    onSave: React.PropTypes.func.isRequired,
    cancelEdit: React.PropTypes.func.isRequired,
    streams: React.PropTypes.object,
    dashboards: React.PropTypes.object,
  },

  mixins: [PermissionsMixin],

  getInitialState() {
    let role = this.props.initialRole;
    if (role === null) {
      // for the create dialog
      role = { name: null, description: null, permissions: [] };
    }
    return {
      role: role,
      initialName: this._safeRoleName(this.props.initialRole),
      filteredStreams: this.props.streams.filter(this._filterStreamsByIP),
      showIP: false,
    };
  },

  componentWillReceiveProps(newProps) {
    this.setState({ role: newProps.initialRole, initialName: this._safeRoleName(newProps.initialRole) });
  },

  _safeRoleName(role) {
    return role === null ? null : role.name;
  },

  _setName(ev) {
    const role = this.state.role;
    role.name = ev.target.value;
    this.setState({ role: this.state.role });
  },
  _setDescription(ev) {
    const role = this.state.role;
    role.description = ev.target.value;
    this.setState({ role: this.state.role });
  },

  _updatePermissions(addedPerms, deletedPerms) {
    const role = this.state.role;
    role.permissions = Immutable.Set(role.permissions)
      .subtract(deletedPerms)
      .union(addedPerms)
      .toJS();
    this.setState({ role: role });
  },

  _saveDisabled() {
    return this.state.role === null || this.state.role.name === null || this.state.role.name === '' || this.state.role.permissions.length === 0;
  },

  _onSave() {
    const streams = this.props.streams;
    const role = this.state.role;
    let addedPerms = Immutable.Set.of();
    let deletedPerms = Immutable.Set.of();
    const permissions = role.permissions;
    permissions.forEach((perm) => {
      const p = perm.split(":");
      const target = p[0];
      const op = p[1];
      const streamId = p[2];
      if (target == "streams"){
        streams.forEach((stream) => {
          if (stream.id == streamId){
            if (stream.title.indexOf("_IP:") >= 0){
              const toDelete = `${target}:${op}:${streamId}`;
              deletedPerms = deletedPerms.add(toDelete);
            }else if (stream.title.indexOf("_Group:") >= 0) {
              stream.rules.forEach((rule) => {
                const title = "_IP:"+rule.value;
                streams.forEach((stream) => {
                  if (stream.title == title){
                    const toAdd = `${target}:${op}:${stream.id}`;
                    addedPerms = addedPerms.add(toAdd);
                  }
                });
              });
            }
          }
        });
      }
    });
    role.permissions = Immutable.Set(role.permissions)
      .subtract(deletedPerms)
      .union(addedPerms)
      .toJS();
    this.props.onSave(this.state.initialName, role);
  },

  _filterStreamsByIP(stream){
    if (!stream.title.startsWith("_IP:")){
      return stream;
    }
  },

  _showIPToggle() {
    if (!this.state.showIP){
      this.setState({
        filteredStreams:this.props.streams,
        showIP: !this.state.showIP,
      });
    }else {
      this.setState({
        filteredStreams:this.props.streams.filter(this._filterStreamsByIP),
        showIP: !this.state.showIP,
      });
    }
  },

  render() {
    let titleText;
    if (this.state.initialName === null) {
      titleText = 'Create a new role';
    } else {
      titleText = `Edit role ${this.state.initialName}`;
    }

    const saveDisabled = this._saveDisabled();
    let saveDisabledAlert = null;
    if (saveDisabled) {
      saveDisabledAlert = (
        <Alert bsStyle="warning" style={{ marginBottom: 10 }}>
          Please name the role and select at least one permission to save it.
        </Alert>
      );
    }

    return (
      <Row>
        <Col md={12}>
          <h1>{titleText}</h1>
          <div style={{ marginTop: 10 }}>
            <Input id="role-name" type="text" label="Name" onChange={this._setName} value={this.state.role.name}
                   required />
            <Input id="role-description" type="text" label="Description" onChange={this._setDescription}
                   value={this.state.role.description} />

            <FormGroup>
              <ControlLabel>Permissions</ControlLabel>
              <HelpBlock>Select the permissions for this role</HelpBlock>
              <Input type="checkbox" label="show ALL streams" onChange={this._showIPToggle} />
              <HelpBlock>Streams generated by collector ip will not shown by default. click here to show all streams</HelpBlock>
            </FormGroup>
            <PermissionSelector streams={this.state.filteredStreams}
                                dashboards={this.props.dashboards}
                                permissions={Immutable.Set(this.state.role.permissions)}
                                onChange={this._updatePermissions}
            />
            <hr />
            {saveDisabledAlert}
            <Button onClick={this._onSave} style={{ marginRight: 5 }} bsStyle="primary" disabled={saveDisabled}>
              Save
            </Button>
            <Button onClick={this.props.cancelEdit}>Cancel</Button>
          </div>
        </Col>
      </Row>);
  },
});

export default EditRole;
